"""
Django settings for mastermind project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from .settings import *

TESTING = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mastermind_test',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'newpassword'
    }
}